Fix/datatable
SmartTechnologyLab/opodatkuvayco-frontend pull request #41
Opened 2024-07-24 13:18 UTC by ZadorozhnyiYevhenii

2024-07-26 14:53 UTC, P0TER commented on src/components/TestDataTableForUser/TestDataTableForUser.test.ts
> +})
Сложно оценить тесты, можем потом пройтись по ним, кажется, часть может быть не совсем честными или хрупкими, обсудим, так же возможно, часть из них, возможно, и не нужна.

Круто, что пишешь в функциональном стиле даже обычные циклы. Ну и про моки можем поговорить как лучше можна их генрировать, в принципе getDeal хороший пример

2024-07-26 15:38 UTC, ZadorozhnyiYevhenii commented on src/components/TestDataTableForUser/TestDataTableForUser.test.ts
> +})
Еще добавляю снепшоты. Можем созваниться когда тебе будет удобно

2024-07-29 17:39 UTC, P0TER requested changes

2024-07-29 17:39 UTC, P0TER commented on src/components/TestDataTableForUser/__snapshots__/TestDataTableForUser.test.ts.snap
> +exports[`Test DataTable for user > Small table contains particular columns 2`] = `true`;
Обсудим и снепшоты))

2024-09-09 10:46 UTC, P0TER approved these changes

2024-09-11 19:29 UTC, merged